import {api,escapeHTML as esc,live,message,submit} from './client.js';
import {prepareAppLogo} from './app-logo-image.js';
import './community.css';
const card='community-card';
const fields=`<label>App name<input name="name" maxlength="80" required></label><label>What does it do?<textarea name="description" maxlength="1000" required></textarea></label><label>App Store or demo link (optional)<input name="url" type="url" placeholder="https://…"></label>`;
const link=p=>p.url&&/^https:\/\//.test(p.url)?`<a class="community-action" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Open app or demo ↗</a>`:'';
export function setupShowcase(){
  const dialog=document.createElement('dialog');dialog.className='community-dialog';document.body.append(dialog);
  dialog.addEventListener('click',e=>{if(e.target===dialog||e.target.closest('[data-close]'))dialog.close();});
  let down;
  document.addEventListener('pointerdown',e=>{if(e.target.closest('.physics-icon-item'))down={x:e.clientX,y:e.clientY};});
  async function open(item){try{const logos=await api('/api/app-logos'),p=logos.find(x=>x.id===item.dataset.projectId);if(!p)return;dialog.innerHTML=`<button data-close class="community-close" aria-label="Close app details">×</button><img class="community-logo" src="${esc(p.imageUrl)}" alt=""><h2>${esc(p.name)}</h2><p class="community-muted">Built by ${esc(p.creator||'the club community')}</p><p>${esc(p.description||'A project built by our club community.')}</p>${link(p)}`;dialog.showModal();}catch(e){message(e);}}
  document.addEventListener('click',e=>{const item=e.target.closest('.physics-icon-item');if(item&&(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)<8))open(item);down=null;});
  document.addEventListener('keydown',e=>{const item=e.target.closest('.physics-icon-item');if(item&&['Enter',' '].includes(e.key)){e.preventDefault();open(item);}});
}
export function renderMemberProfile(me,projects){
  const target=document.getElementById('member-profile');if(!target)return;
  target.innerHTML=`<article class="${card}"><h2>${esc(me.name)}</h2><p class="community-muted">${esc(me.email||'')} · Club member</p><p>${me.badgeProgress.completedEvents} events attended · ${me.badges.length} badges earned · ${projects.filter(p=>p.status==='approved').length} published projects</p></article><section class="${card}"><h2>My projects</h2>${projects.length?projects.map(p=>`<article class="community-project"><img src="${esc(p.imageUrl)}" alt="" width="64" height="64"><div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><span class="community-muted">${esc(p.status==='pending'?'Awaiting approval':p.status==='approved'?'Published':'Not approved — you can submit a revised project')}</span>${link(p)}</div></article>`).join(''):'<p class="community-muted">Submit your first app below.</p>'}</section><section class="${card}"><h2>Earned badges</h2>${me.badges.length?me.badges.map(b=>`<p>${esc(b.name)} · ${esc(b.eventTitle||'Club achievement')}</p>`).join(''):'<p class="community-muted">Your badges appear after confirmed attendance.</p>'}</section><section class="${card}"><h2>Attended events</h2>${me.registeredEvents.filter(e=>e.attended).map(e=>`<p>${esc(e.title)} · ${esc(new Date(e.date).toLocaleDateString())}</p>`).join('')||'<p class="community-muted">No attended events yet.</p>'}</section>`;
}
export function setupProjectSubmission(refresh){
  const form=document.getElementById('project-submit-form');if(!form)return;
  form.innerHTML=`${fields}<label>App logo · automatically fitted to 1024 × 1024<input name="logo" type="file" accept="image/png,image/jpeg,image/webp" required></label><p class="community-muted">The team reviews your project before publishing it on the landing page.</p><button class="community-action" type="submit">Submit for review</button>`;
  form.addEventListener('submit',event=>submit(event,async()=>{const data=new FormData(form),imageUrl=await prepareAppLogo(data.get('logo'));await api('/api/me/projects',{method:'POST',body:JSON.stringify({name:data.get('name'),description:data.get('description'),url:data.get('url'),imageUrl})});form.reset();await refresh();message('Project submitted for admin review.');}));
}
export function setupAdminCommunity(){
  const main=document.querySelector('main');if(!main)return;
  if(document.getElementById('appLogosList')){
    const section=document.createElement('section');section.className=card;section.innerHTML='<h2>Project submissions</h2><label>Review status<select id="project-status"><option value="pending">Awaiting approval</option><option value="all">All submissions</option><option value="approved">Published</option><option value="rejected">Not approved</option></select></label><div id="project-reviews"></div>';main.append(section);
    let projects=[];
    const render=()=>{const rows=projects.filter(p=>document.getElementById('project-status').value==='all'||p.status===document.getElementById('project-status').value);document.getElementById('project-reviews').innerHTML=rows.length?rows.map(p=>`<article class="community-project"><img src="${esc(p.imageUrl)}" width="64" height="64" alt=""><div><h3>${esc(p.name)}</h3><p>${esc(p.creator)} · ${esc(p.status)}</p><p>${esc(p.description)}</p>${link(p)}<div class="community-actions">${p.status!=='approved'?`<button data-review="${esc(p.id)}" data-status="approved">Approve & publish</button>`:''}${p.status!=='rejected'?`<button data-review="${esc(p.id)}" data-status="rejected">${p.status==='approved'?'Unpublish':'Reject'}</button>`:''}</div></div></article>`).join(''):'<p class="community-muted">No submissions in this category.</p>';};
    document.getElementById('project-status').onchange=render;
    live(async()=>{projects=await api('/api/admin/projects');render();},{role:'admin',collections:['projects']});
    section.addEventListener('click',e=>{const b=e.target.closest('[data-review]');if(!b)return;b.disabled=true;api('/api/admin/projects/'+b.dataset.review,{method:'PUT',body:JSON.stringify({status:b.dataset.status})}).then(()=>message('Project review saved.')).catch(message).finally(()=>b.disabled=false);});
    const directory=document.createElement('section');directory.className=card;directory.innerHTML='<h2>Members</h2><div id="member-directory"></div>';main.append(directory);
    live(async()=>{const members=await api('/api/admin/students');document.getElementById('member-directory').innerHTML=`<table><thead><tr><th>Name</th><th>Email</th><th>Joined</th></tr></thead><tbody>${members.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.email)}</td><td>${esc(m.joinedDate?new Date(m.joinedDate).toLocaleDateString():'')}</td></tr>`).join('')}</tbody></table>`;},{role:'admin',collections:['members']});
  }
  setupTableFilters(main);
  const logoForm=document.getElementById('addAppLogoModal')?.querySelector('form');
  if(logoForm){const extra=document.createElement('div');extra.className='community-fields';extra.innerHTML='<label>Creator<input id="appLogoCreator" maxlength="100"></label><label>App description<textarea id="appLogoDescription" maxlength="1000"></textarea></label><label>App Store or demo link<input id="appLogoUrl" type="url" placeholder="https://…"></label>';document.getElementById('appLogoName').parentElement.after(extra);}
  const dialog=document.createElement('dialog');dialog.className='community-dialog';dialog.innerHTML=`<button class="community-close" data-close aria-label="Close project editor">×</button><h2>Edit app showcase</h2><form>${fields}<label>Creator<input name="creator" maxlength="100"></label><button type="submit" class="community-action">Save details</button></form>`;document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();
  document.getElementById('appLogosList')?.addEventListener('click',async e=>{const b=e.target.closest('[data-edit-showcase]');if(!b)return;try{const p=(await api('/api/app-logos')).find(p=>p.id===b.dataset.editShowcase);if(!p)return;dialog.dataset.id=p.id;for(const key of ['name','description','url','creator'])dialog.querySelector(`[name=${key}]`).value=p[key]||'';dialog.showModal();}catch(error){message(error);}});
  dialog.querySelector('form').onsubmit=event=>submit(event,async()=>{const data=Object.fromEntries(new FormData(event.target));await api('/api/admin/app-logos/'+dialog.dataset.id,{method:'PUT',body:JSON.stringify(data)});dialog.close();message('App details saved.');});
}
function setupTableFilters(main){
  const attach=()=>{for(const table of main.querySelectorAll('table')){if(table.dataset.filtered)continue;table.dataset.filtered='true';const bar=document.createElement('div');bar.className='community-filters';bar.innerHTML='<label>Search<input type="search" placeholder="Search names, emails, events…"></label>';const isRegistration=Boolean(table.closest('#registrations-list'));if(isRegistration)bar.innerHTML+='<label>Attendance<select><option value="all">All registrations</option><option value="attended">Checked in</option><option value="waiting">Awaiting check-in</option><option value="cancelled">Cancelled</option></select></label><label>Event<select data-event><option value="">All events</option></select></label>';table.before(bar);const apply=()=>{const search=bar.querySelector('input').value.toLowerCase(),status=bar.querySelector('select:not([data-event])')?.value,event=bar.querySelector('[data-event]')?.value;const rows=[...table.querySelectorAll('tbody tr')];if(isRegistration){const select=bar.querySelector('[data-event]'),names=[...new Set(rows.map(r=>r.cells[0]?.textContent.trim()))].filter(Boolean);if(select.options.length!==names.length+1){select.innerHTML='<option value="">All events</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('');select.value=event||'';}}let count=0;for(const row of rows){const checkbox=row.querySelector('[data-attendance]'),cancelled=row.textContent.includes('Cancelled');row.hidden=!row.textContent.toLowerCase().includes(search)||(event&&row.cells[0]?.textContent.trim()!==event)||(status==='attended'&&!checkbox?.checked)||(status==='waiting'&&(!checkbox||checkbox.checked))||(status==='cancelled'&&!cancelled);if(!row.hidden)count++;}bar.querySelector('output').textContent=`${count} results`;};const output=document.createElement('output');bar.append(output);bar.addEventListener('input',apply);bar.addEventListener('change',apply);table.addEventListener('change',apply);new MutationObserver(apply).observe(table,{childList:true,subtree:true});apply();}};
  new MutationObserver(attach).observe(main,{childList:true,subtree:true});attach();
}
