import {api,escapeHTML as esc,live,youtubeVideoId} from './client.js';
if(document.getElementById('resources-container'))live(async()=>{
  const resources=await api('/api/resources');
  const groups=new Map();for(const resource of resources){const category=resource.category||'General';if(!groups.has(category))groups.set(category,[]);groups.get(category).push(resource);}
  document.getElementById('resources-container').innerHTML=resources.length?[...groups].map(([category,items])=>`<section class="resource-section"><h2 class="resource-section-title">${esc(category)}</h2><div class="resources-grid">${items.map(r=>{const videoId=youtubeVideoId(r.url);return `<a class="resource-card ${videoId?'resource-card-video':''}" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${videoId?`<div class="resource-thumbnail"><img src="https://i.ytimg.com/vi/${videoId}/hqdefault.jpg" alt="" loading="lazy"><span class="resource-play" aria-hidden="true">▶</span></div><div class="resource-card-content"><span class="resource-source">Apple Developer · Video</span>`:'<div class="resource-card-content"><div class="resource-icon">↗</div>'}<h3 class="resource-title">${esc(r.title)}</h3><p class="resource-desc">${esc(r.desc||r.category)}</p><div class="resource-link">${videoId?'Watch video':'View resource'} →</div></div></a>`;}).join('')}</div></section>`).join(''):'<p>Learning resources will appear here when the club publishes them.</p>';
});
if(document.getElementById('team-container'))live(async()=>{
  const members=await api('/api/team');
  const roles=['Club President','Vice President & Technical Lead','Design Lead','Events Coordinator'];
  document.getElementById('team-container').innerHTML=members.length?members.map(m=>`<article class="team-member"><h3 class="member-name">${esc(m.name)}</h3><div class="member-role">${esc(m.role)}</div><p class="member-bio">${esc(m.bio)}</p></article>`).join(''):roles.map(role=>`<article class="team-member"><div class="member-photo member-photo-placeholder" aria-hidden="true">✦</div><h3 class="member-name">Profile coming soon</h3><div class="member-role">${esc(role)}</div><p class="member-bio">Details will be added when this role is confirmed by the club.</p></article>`).join('');
});
